### ISSUE TITLE
Environments files for production and development are not ignored

### ISSUE THREAD

**Issue by sametcodes** [yasinelbuz/github-insight#1]
[.env.production](https://github.com/yasinelbuz/github-insight/blob/master/.env.production) and [.env.development](https://github.com/yasinelbuz/github-insight/blob/master/.env.development) files are not ignored. Luckily there is no credential in the files ― only variables with localhost, but it might cause problems for future developments. They must be ignored.

**Comment by yasinelbuz** [comment]
Removed env.production and env.development files.
thanks @sametcodes
